### ISSUE TITLE
Missing import, as and from keywords

### ISSUE THREAD

**Issue by rope-hmg** [hrvolapeter/javascript-lexer#1]
**Is your feature request related to a problem? Please describe.**
I am trying to parse some JavaScript and I'm getting `IdentifierName("")` tokens when I should be getting keywords.

**Describe the solution you'd like**
I would like this library to support the `import`, `as` and `from` keywords.

Tanks 😄

**Comment by hrvolapeter** [comment]
I will check this could be something small to fix, can you provide some small code sample that is failing?

**Comment by rope-hmg** [comment]
I have a js file with the following code at the top of the file.

    import * as helpers from './helpers.js';

The tokens I'm getting for this are `IdentifierName("import")`, `Star`, `IdentifierName("as")`, `IdentifierName("helpers")`, `IdentifierName("from")`, `StringLiteral("./helpers.js")` and `Semicolon`.

I was expecting something more like: `KImport`, `Star`, `KAs`, `IdentifierName("helpers")`, `KFrom`, `StringLiteral("./helpers.js")` and `Semicolon`.

Thanks :)

**Comment by hrvolapeter** [comment]
I've added missing keywords from your example, added test and published new version. It's fixed in version 0.1.7.
